### ISSUE TITLE
Edit search bar for job hunt section

### ISSUE THREAD

**Issue by Adhetya** [CSwala/cswala.github.io#108]
Need to scroll a lot to see content which is not a good user experience. Adding a search bar would make it better.

<img width="1376" alt="Screenshot 2022-05-27 at 7 28 40 PM" src="https://user-images.githubusercontent.com/20537150/170714475-04c242a8-fe55-431c-8c87-6e3bd016d837.png">

I am a GSOCC 22 contributor. Please assign this issue to me.

**Comment by riturajjain2000** [comment]
The search bar is there , but needs to be made consistent with the rest of the design !
