### ISSUE TITLE
improve login page UI

### ISSUE THREAD

**Issue by Abhirv08** [CSwala/cswala.github.io#64]
![Screenshot 2021-12-04 095752](https://user-images.githubusercontent.com/81900610/144705424-0afc88d5-1306-484d-a039-23dd61ae835a.png)

Here, in login page, i suppose on hovering to the google logo or github logo, it should stand out from another like becoming a little bit big in size.

If the idea seems valid to you please assign it to me so that i can work on it. @riturajjain2000  @5tupidbrain

**Comment by riturajjain2000** [comment]
we are focusing on completing the site first , then well go ahead with design changes
