### ISSUE TITLE
authentication with github

### ISSUE THREAD

**Issue by yogitasaini** [CSwala/cswala.github.io#69]
Please assign this task to me

**Comment by the-halfbloodprince** [comment]
@riturajjain2000 this can be easily done with either Next Auth or even better, Auth0, which will enable us to integrate more OAuth options like Google, Facebook etc as well from the OAuth dashboard itself without tweaking much in the code. So in case this is open, I am willing to contribute.

**Comment by Abh1shekSingh** [comment]
@riturajjain2000 Please Assign the task to me. It been pending since 1 march no one has worked. so please assign to me
