### ISSUE TITLE
Description line height 

### ISSUE THREAD

**Issue by Debajyoti14** [CSwala/cswala.github.io#70]
At 829 px the Description where CSwaala line looks creepy where line-height should be a little greater.
I would like to do that.

**Comment by Debajyoti14** [comment]
I have fixed the issue with PR
Merge if you find it right

**Comment by riturajjain2000** [comment]
> I have fixed the issue with PR Merge if you find it right

please provide the pr link

**Comment by Debajyoti14** [comment]
https://github.com/CSwala/CSwala-website/pull/76
https://github.com/CSwala/CSwala-website/pull/77
This is the link of the both of the PR I issued
