### ISSUE TITLE
Enhancement: Add custom scroll bar

### ISSUE THREAD

**Issue by TG922** [CSwala/cswala.github.io#74]
### Description

- I want to add custom scroll bar for this website.

### Screenshot

- Please assign me on this issue under GSSOC '22.

![Image](https://user-images.githubusercontent.com/70098839/156426226-811ca67a-d567-40ee-b783-5cce1aaf71fc.PNG)

**Comment by trDalmi** [comment]
Can u assign it to me under the tag of GSSOC22.

**Comment by TG922** [comment]
@riturajjain2000 I'm Almost done, I will send PR regarding this tomorrow morning!!

**Comment by TG922** [comment]
I will send PR regarding this ASAP today sorry for the delay I was busy
